---
- name: Install Ingress Nginx
  command: |
    kubectl apply -f  'https://raw.githubusercontent.com/dottgonzo/ansible-role-setup-custom-K8s-proxy/master/stacks/{{ ingress_nginx_api_filename }}>
  changed_when: False

- name: Install Cert Manager
  command: |
    kubectl apply -f  'https://raw.githubusercontent.com/dottgonzo/ansible-role-setup-custom-K8s-proxy/master/stacks/cert-manager.yml>
  changed_when: False

- name: Wait for Running state
  register: proxyboot

  shell: |
    set -o pipefail
    kubectl get pods -n cert-manager | grep -c Running
  until: proxyboot.stdout == '3'
  delay: 5
  retries: 100
  changed_when: false