---

- name: Install Ingress Nginx
  include_role:
    name: dottgonzo.ansible_role_kubectl_from_local_file
  vars:
    local_file_path: "~/.ansible/roles/dottgonzo.ansible_role_setup_custom_k8s_proxy/stacks/{{ ingress_nginx_api_filename }}"

- name: install Cert Manager
  include_role:
    name: dottgonzo.ansible_role_kubectl_from_local_file
  vars:
    local_file_path: '~/.ansible/roles/dottgonzo.ansible_role_setup_custom_k8s_proxy/cert-manager.yml'

- name: Wait for Running state
  register: proxyboot

  shell: |
    set -o pipefail
    kubectl get pods -n cert-manager | grep -c Running
  until: proxyboot.stdout == '3'
  delay: 5
  retries: 100
  changed_when: false