---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
  namespace: ingress-nginx

spec:
  selector:
    matchLabels:
      run: ingress-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: ingress-nginx
    spec:
      containers:
      - name: ingress-nginx
        image: containous/whoami
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    run: ingress-nginx
spec:
  ports:
  - port: 80
  selector:
    run: ingress-nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:

  rules:
  - host: whoami.local
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress-nginx
          servicePort: 80

